input:
  path: ./input.csv
output:
  format: sqlite
  path: ./output.db
mapping:
  path: ../mapping.yml
batch_size: 150000
write_header: true
logging: True
database:
  type: sqlite
  sql_statement_path: ./simple.sql
  output_table: output
