"""Generate settings-schema reference pages from the JSON Schemas (single source of truth).

ODS_Tools owns the settings schemas in ``ods_tools/data/*_settings_schema.json``. Rather than
hand-maintain field tables, this extension walks each schema at build time and writes MyST
Markdown into ``reference/_generated/`` which the reference pages include. Edit the schema
JSON, not the generated Markdown.

Runs on the Sphinx ``config-inited`` event; also runnable standalone for quick checks.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir, os.pardir))
DATA_DIR = os.path.join(REPO_ROOT, "ods_tools", "data")
OUT_DIR = os.path.join(HERE, os.pardir, "reference", "_generated")

SCHEMAS = [
    ("model_settings_schema.json", "model_settings.md"),
    ("analysis_settings_schema.json", "analysis_settings.md"),
    ("combine_settings_schema.json", "combine_settings.md"),
]

MAX_DEPTH = 4  # how deep to expand nested objects into their own subsections


def _cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ").replace("\r", " ").strip()


def _resolve(schema, root):
    """Follow a ``$ref`` (and merge a single-branch allOf) to a concrete schema."""
    seen = 0
    while isinstance(schema, dict) and "$ref" in schema and seen < 10:
        ref = schema["$ref"]
        node = root
        for part in ref.lstrip("#/").split("/"):
            if isinstance(node, dict) and part in node:
                node = node[part]
            else:
                return schema  # unresolvable; leave as-is
        schema = node
        seen += 1
    if isinstance(schema, dict) and "allOf" in schema and len(schema["allOf"]) == 1:
        merged = {k: v for k, v in schema.items() if k != "allOf"}
        merged.update(_resolve(schema["allOf"][0], root))
        return merged
    return schema


def _type_str(s):
    if "enum" in s:
        return "enum"
    t = s.get("type")
    if isinstance(t, list):
        return " / ".join(t)
    if t == "array":
        items = s.get("items", {})
        it = items.get("type") if isinstance(items, dict) else None
        return f"array[{it}]" if it else "array"
    if t:
        return t
    for k in ("oneOf", "anyOf"):
        if k in s:
            return " / ".join(sorted({b.get("type", "object") for b in s[k] if isinstance(b, dict)}))
    return "object" if "properties" in s else ""


def _constraints(s):
    bits = []
    if "enum" in s:
        bits.append("one of: " + ", ".join(f"`{e}`" for e in s["enum"]))
    if "default" in s:
        bits.append(f"default `{s['default']}`")
    for k in ("minimum", "maximum"):
        if k in s:
            bits.append(f"{k} {s[k]}")
    return "; ".join(bits)


def _object_children(name, s, root):
    """Return (child_object_schema, heading) if this property expands, else None."""
    s = _resolve(s, root)
    if s.get("type") == "object" and "properties" in s:
        return s
    if s.get("type") == "array":
        items = _resolve(s.get("items", {}), root)
        if isinstance(items, dict) and "properties" in items:
            return items
    return None


def _render(name, schema, root, level, out, path):
    """Render an object schema: a properties table plus subsections for nested objects."""
    schema = _resolve(schema, root)
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    header = "#" * min(level, 6)
    if path:
        out.append(f"\n{header} {path}\n")
    desc = schema.get("description") or schema.get("title")
    if desc and path:
        out.append(_cell(desc) + "\n")
    rows, nested = [], []
    for pname, praw in props.items():
        ps = _resolve(praw, root)
        rows.append([f"`{pname}`", _type_str(ps), "Yes" if pname in required else "",
                     _constraints(ps), ps.get("description") or ps.get("title") or ""])
        child = _object_children(pname, praw, root)
        if child is not None and level < MAX_DEPTH:
            nested.append((pname, child))
    if rows:
        out.append("| Field | Type | Required | Constraints | Description |")
        out.append("| --- | --- | --- | --- | --- |")
        for r in rows:
            out.append("| " + " | ".join(_cell(c) for c in r) + " |")
    for pname, child in nested:
        child_path = f"{path}.{pname}" if path else pname
        _render(pname, child, root, level + 1, out, child_path)


def generate_one(src, dst):
    with open(os.path.join(DATA_DIR, src), encoding="utf-8") as fh:
        schema = json.load(fh)
    out = [f"<!-- generated by _ext/gen_settings_reference.py from ods_tools/data/{src} -->"]
    _render(schema.get("title", src), schema, schema, level=1, out=out, path="")
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, dst), "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    # count fields rendered
    return sum(1 for line in out if line.startswith("| `"))


def run(app=None, config=None):
    total = {dst: generate_one(src, dst) for src, dst in SCHEMAS}
    msg = "[gen_settings_reference] " + ", ".join(f"{k}:{v} fields" for k, v in total.items())
    if app is not None:
        from sphinx.util import logging
        logging.getLogger(__name__).info(msg)
    else:
        print(msg)


def setup(app):
    app.connect("config-inited", run)
    return {"parallel_read_safe": True, "parallel_write_safe": True}


if __name__ == "__main__":
    run()
