transformations:
  loc: # Transformation name
    input_format:
      name: Cede_Location
      version: 10.0.0
    output_format:
      name: OED_Location
      version: 3.0.2
    runner:
      batch_size: 150000 # Number of rows to process in a single batch
    extractor:
      options:
        path: ./cede_location_1000.csv # Path to the input file
        quoting: minimal
    loader:
      options:
        path: ./oed_location_1000.csv # Path to the output file
        quoting: minimal
  acc: # Transformation name
    input_format:
      name: Cede_Contract
      version: 10.0.0
    output_format:
      name: OED_Contract
      version: 3.0.2
    runner:
      batch_size: 10000
    extractor:
      options:
        path: ./cede_contract_1000.csv
        quoting: minimal
    loader:
      options:
        path: ./oed_contract_1000.csv
        quoting: minimal
