input:
  format: sqlite
  path: ./simple.sql
output:
  path: ./output.csv
mapping:
  path: ../mapping.yml
batch_size: 150000
write_header: true
logging: True
database:
  type: sqlite
  sql_statement_path: "./simple.sql"
  absolute_path_database: "./input.db"
