name: ODS-tools Testing


on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  test:
    name: Run Pytest
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Download package
      uses: actions/download-artifact@v3
      with:
        name: bin_package
        path: ${{ github.workspace }}/

    # Temp build step
    - name: Install LOT3 package
      run: |
        pip install pyspark dask
        pip install -v git+https://git@github.com/OasisLMF/OasisPlatformLot3.git@develop#egg=lot3

    - name: install package
      run: pip install ${{ needs.build.outputs.whl_filename }}

    - name: Install test deps
      run: pip install -r tests/requirements.in

    - name: Run tests
      run: pytest -v
